# docker compose file to run the jqextractor service
# and setup a rabbitmq service for testing

# Define the services
services:
  # Define the group-and-verify service
  group-and-verify:
    # Use the Group and Verify image
    image: ${GROUPANDVERIFY_IMAGE}
    # Build the image from the Dockerfile
    build:
      # Use the root directory as the context
      context: ../../.
      # Use the group-and-verify Dockerfile
      dockerfile: GroupAndVerify/nginxbuild/Dockerfile.GroupAndVerify.nginx
    depends_on:
      rabbitmq:
        condition: service_healthy
    # Set the container name
    container_name: group-and-verify
    # Mount the config directory to the container
    volumes:
      - ./config:/config
      - ./certs/ca_certificate.pem:/certs/rootCA.crt
      - ./certs/client_certificate.pem:/etc/ssl/certs/nginx.crt
      - ./certs/private_key.pem:/etc/ssl/certs/nginx.key
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    # Set the entrypoint
    entrypoint: ["/bin/sh", "-c", "cat /certs/rootCA.crt >> /etc/ssl/certs/ca-certificates.crt && nginx && /group-and-verify --config /config/config.json"]