# docker compose file to run the jqextractor service
# and setup a rabbitmq service for testing

# Define the services
services:
  # Define the group-and-verify service
  group-and-verify:
    # Use the Group and Verify image
    image: ${GROUPANDVERIFY_IMAGE}
    # Build the image from the Dockerfile
    build:
      # Use the root directory as the context
      context: ../../.
      # Use the group-and-verify Dockerfile
      dockerfile: GroupAndVerify/Dockerfile.GroupAndVerify
    depends_on:
      rabbitmq:
        condition: service_healthy
    # Set the container name
    container_name: group-and-verify
    # Mount the config directory to the container
    volumes:
      - ./config:/config
    # Set the entrypoint
    entrypoint: ["/group-and-verify", "--config", "/config/config.json"]
  # Define the rabbitmq service
  rabbitmq:
    # Use the rabbitmq:4.0-management image
    image: rabbitmq:4.0-management
    # Set the container name
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10
    # Expose the ports
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json