@startuml
namespace JSONExtractor {
    struct JQTransformer {
        -gojq.Code jqProgram
        -Pushable pushable
        +error AddPushable(Pushable)
        +(sync.WaitGroup error) SendTo(*AppData)
        +error Serve()
    }
}
namespace Server {
    interface CompletionHandler {
        +error Complete(any, error)
    }
    struct AppData {
        -any data
        +CompletionHandler completionHandler
        +any GetData()
        +CompletionHandler GetCompletionHandler()
    }
    interface Server {
        +error Serve()
    }
    interface Pullable {
        +error AddPushable(Pushable)
    }
    interface Pushable {
        +(sync.WaitGroup error) SendTo(*AppData)
    }
    interface SourceServer {
        +error AddPushable(Pushable)
        +error Serve()
    }
    interface SinkServer {
        +(sync.WaitGroup error) SendTo(*AppData)
        +error Serve()
    }
    interface PipeServer {
        +error AddPushable(Pushable)
        +(sync.WaitGroup error) SendTo(*AppData)
        +error Serve()
    }
    interface Producer {
        +error Setup(ProducerConfig)
        +(sync.WaitGroup error) SendTo(*AppData)
        +error Serve()
    }
    interface Consumer {
        +error AddPushable(Pushable)
        +error Setup(ConsumerConfig)
        +error Serve()
    }
    struct ProducerServer {
        -map[string]Producer producerMap
        +(sync.WaitGroup error) SendTo(*AppData)
        +error Serve()
    }
    struct ConsumerServer {
        -map[string]Consumer consumersMap
        +error AddPushable(Pushable)
        +error Serve()
    }
    interface ProducerConfig {
        +error IngestConfig(any)
    }
    interface ConsumerConfig {
        +error IngestConfig(any)
    }
}
Server.CompletionHandler *-- Server.AppData
Server.AppData *-- Server.Pushable
Server.Server <|-- Server.SourceServer
Server.Pushable *-- Server.Pullable
Server.Pullable <|-- Server.SourceServer
Server.Server <|-- Server.SinkServer
Server.Pushable <|-- Server.SinkServer
Server.Pushable <|-- Server.PipeServer
Server.Pullable <|-- Server.PipeServer
Server.Server <|-- Server.PipeServer

Server.SinkServer <|-- Server.Producer
Server.Producer *-- Server.ProducerServer
Server.SinkServer <|-- Server.ProducerServer
Server.SourceServer <|-- Server.ConsumerServer
Server.Consumer *-- Server.ConsumerServer
Server.SourceServer <|-- Server.Consumer

Server.PipeServer <|-- JSONExtractor.JQTransformer
Server.Pushable *-- JSONExtractor.JQTransformer


Server.ConsumerConfig *-up- Server.Consumer
Server.ProducerConfig *-up- Server.Producer
@enduml