@startuml
namespace Server {
    interface CompletionHandler {
        +error Complete(any, error)
    }
    struct WaitGroupCompletionHandler {
        -sync.WaitGroup wg
        -any data
        -error error
        -bool isComplete
        +error Complete(any, error)
    }
    struct AppData {
        -any data
        +CompletionHandler completionHandler
        +any GetData()
        +CompletionHandler GetCompletionHandler()
    }
    interface Server {
        +error Serve()
        +error Setup(Config)
    }
    interface Pullable {
        +error AddPushable(Pushable)
    }
    interface Pushable {
        +error SendTo(*AppData)
    }
    interface SourceServer {
        +error AddPushable(Pushable)
        +error Serve()
        +error Setup(Config)
    }
    interface SinkServer {
        +error SendTo(*AppData)
        +error Serve()
        +error Setup(Config)
    }
    interface PipeServer {
        +error AddPushable(Pushable)
        +error SendTo(*AppData)
        +error Serve()
        +error Setup(Config)
    }
    struct MapSinkServer {
        -map[string]SinkServer sinkServerMap
        +error SendTo(*AppData)
        +error Serve()
        +error Setup(Config)
    }
    interface Config {
        +error IngestConfig(map[string]any)
    }
    struct SelectProducerConfig {
        +string Map
        +string Type
        +Config Config
        +error IngestConfig(map[string]any)
    }
    struct SetupProducersConfig {
        +IsMapping bool
        +[]SelectProducerConfig SelectProducerConfigs
        +error IngestConfig(map[string]any)
    }
    struct SelectConsumerConfig {
        +string Type
        +Config Config
        +error IngestConfig(map[string]any)
    }
    struct SetupConsumersConfig {
        +[]SelectConsumerConfig SelectConsumerConfigs
        +error IngestConfig(map[string]any)
    }
    struct AppConfig {
        +SetupProducersConfig SetupProducersConfig
        +SetupConsumersConfig SetupConsumersConfig
        +Config PipeServerConfig
        +error IngestConfig(map[string]any)
    }
}
Server.CompletionHandler <|-- Server.WaitGroupCompletionHandler
Server.CompletionHandler *-- Server.AppData
Server.AppData *-- Server.Pushable
Server.Server <|-- Server.SourceServer
Server.Pushable *-- Server.Pullable
Server.Pullable <|-- Server.SourceServer
Server.Server <|-- Server.SinkServer
Server.Pushable <|-- Server.SinkServer
Server.Pushable <|-- Server.PipeServer
Server.Pullable <|-- Server.PipeServer
Server.Server <|-- Server.PipeServer

Server.SinkServer *-- Server.MapSinkServer
Server.SinkServer <|-- Server.MapSinkServer

Server.Server *-- Server.Config
Server.Config *-- Server.SelectProducerConfig
Server.Config *-- Server.SelectConsumerConfig
Server.SetupProducersConfig *-- Server.AppConfig
Server.SetupConsumersConfig *-- Server.AppConfig
Server.SelectProducerConfig *-- Server.SetupProducersConfig
Server.SelectConsumerConfig *-- Server.SetupConsumersConfig
@enduml