@startuml
    partition Server {
        split
        -[hidden]->
        package Server {
            group RunServer(SourceServer, PipeServer, SinkServer) error {
                :Add Receiver to SourceServer from PipeServer;
                :Add Receiver to PipeServer from SinkServer;
                :Call Serve SinkServer;
                :Call Serve PipeServer;
                :Call Serve SourceServer;
                :Call HandleIncomingData on SinkServer;
                :Call HandleIncomingData on PipeServer;
                detach
            }
            group HandlePushableDataReceipt(Pushable) error {
                :Call GetReceiver on Pushable;
                :Call GetOutChan on Receiver;
                repeat
                    :Receive data from channel;
                    :Call HandleIncomingData of Pushable with AppData;
                repeat while (while data is available in channel)
                :Return nil;
                detach
            }
        }
        split again
        -[hidden]->
        package Producer {
            group getProducerServer(ProducerConfig) (ProducerServer, error) {
                :Create Producers and Producers map using config;
                :Create ProducerServer using Producers map;
                :Return ProducerServer;
                detach
            }
        }
        package Consumer {
            group getConsumerServer(ConsumerConfig) (ConsumerServer, error) {
                :Create Consumers and Consumers map using config;
                :Create ConsumerServer using Consumers map;
                :Return ConsumerServer;
                detach
            }
        }
        end split
    }
@enduml