@startuml
    partition JSON Extractor {
        split
        -[hidden]->
        package main {
            group main() {
                :get config from file;
                :Get producer server using config;
                :Get consumer server using config;
                :Get JQTransformer using config;
                :Start App;
                detach
            }
            group getConfigFromFile(pathToConfig) Config {
                :Read config from file;
                :Separate config into producerConfig,\nconsumerConfig, jqTransformerConfig;
                :Return config;
                detach
            }
        }
        split again
        -[hidden]->
        package JqTransformer {
            group getJQTransformer(JqTransformerConfig) (JQTransformer, error) {
                :Create JQTransformer using config;
                :Return JQTransformer;
                detach
            }
            group Serve(JQTransformer) error {
                :checks if everything is correctly set and finishes;
                detach
            }
            group AddPushable(*JQTransformer, Pushable) error {
                :Add Pushable to JQTransformer instance;
                detach
            }
            group SendTo(*JQTransformer, AppData) error {
                :Extract JSON data from AppData using compiled jqProgram;
                :Create AppData with extracted data and CompletionHandler;
                :Send AppData to Pushable;
                :Return error;
                detach
            }
        }
        end split
    }
@enduml