@startuml
left to right direction
component ConsumerServer {
    component JQTransformerReceiver
}
component JQTransformer {
    component ProducerServerReceiver
}
interface "JQTransformer\nSend Channel" as JQTransformerChannel
component ProducerServer {
}
interface "ProducerServer\nSend Channel" as ProducerServerChannel
interface "Consumption Location" as ConsumptionLocation
interface "Production Location" as ProductionLocation
JQTransformerReceiver -down- JQTransformerChannel : Push to\nchannel
ProducerServerReceiver -down- ProducerServerChannel : Push to\nchannel
JQTransformerChannel )-down- JQTransformer : Pull from\nchannel
ProducerServerChannel )-down- ProducerServer : Pull from\nchannel

ConsumerServer -left- ConsumptionLocation : Consume from\nbroker 
ProducerServer -right- ProductionLocation : Produce to\nbroker
@enduml