@startuml
left to right direction
component ConsumerServer
component JQTransformer {
    component JQExtraction
}
component ProducerServer
interface "Consumption Location" as ConsumptionLocation
interface "Production Location" as ProductionLocation

ConsumerServer -down-> JQExtraction : Send data
JQExtraction -down-> ProducerServer : Send data

ConsumerServer -right- ConsumptionLocation : Consume from\nbroker 
ProducerServer -right- ProductionLocation : Produce to\nbroker
@enduml