@startuml
interface Server.Config {
    +error IngestConfig(map[string]any)
}
interface Server.PipeServer {
    +error AddPushable(Server.Pushable)
    +error SendTo(*Server.AppData)
    +error Serve()
    +error Setup(Server.Config)
}
interface Server.Pushable {
    +error SendTo(*Server.AppData)
}

namespace GroupAndVerify {
    struct GroupApply {
        +string FieldToShare
        +string IdentifyingField
        +string ValueOfIdentifyingField
    } 

    struct GroupAndVerifyConfig {
        -bool orderChildrenByTimestamp
        -map[string]GroupApply groupApplies
        -map[string]bool parentVerifySet
        +error IngestConfig(map[string]any)
    }
    struct GroupAndVerify {
        -GroupAndVerifyConfig config
        -Server.Pushable pushable
        -chan *Task taskChan
        +error AddPushable(Server.Pushable)
        +error SendTo(*Server.AppData)
        +error Serve()
        +error Setup(Server.Config)
    }
    struct Task {
        +IncomingData Node
        +chan error ErrorChan
    }
    struct IncomingData {
        +string TreeId
        +string NodeId
        +string ParentId
        +[]string ChildIds
        +string NodeType
        +int Timestamp
        +map[string]any AppJSON
    }
    struct OutgoingData {
        +string NodeId
        +[]string OrderedChildIds
        +map[string]any AppJSON
    }
}

Server.PipeServer <|-- GroupAndVerify.GroupAndVerify
Server.Pushable *-- GroupAndVerify.GroupAndVerify
Server.Config <|-- GroupAndVerify.GroupAndVerifyConfig
GroupAndVerify.GroupApply *-- GroupAndVerify.GroupAndVerifyConfig
GroupAndVerify.GroupAndVerifyConfig *-- GroupAndVerify.GroupAndVerify
GroupAndVerify.Task *-- GroupAndVerify.IncomingData
GroupAndVerify.GroupAndVerify *-- GroupAndVerify.Task
@enduml