@startuml
left to right direction
component ConsumerServer
component "Group and Verify" as GroupVerify
component ProducerServer
interface "Consumption Location" as ConsumptionLocation
interface "Production Location" as ProductionLocation

ConsumerServer -down-> GroupVerify : Send data
GroupVerify -down-> ProducerServer : Send data

ConsumerServer -right- ConsumptionLocation : Consume from\nbroker 
ProducerServer -right- ProductionLocation : Produce to\nbroker
@enduml