@startuml
interface Server.Config {
    +error IngestConfig(map[string]any)
}
interface Server.PipeServer {
    +error AddPushable(Server.Pushable)
    +error SendTo(*Server.AppData)
    +error Serve()
    +error Setup(Server.Config)
}
interface Server.Pushable {
    +error SendTo(*Server.AppData)
}

namespace Sequencer {
    enum SequenceMethod {
        TIMESTAMP
        ORDEREDCHILDREN
        COMBINATION
    }
    struct SequencerConfig {
        -SequenceMethod sequenceMethod
        -string inputSchema
        -string outputSchema
        -map[string]string inputToOutputMap
        +error IngestConfig(map[string]any)
    }
    struct Sequencer {
        -SequencerConfig config
        -Server.Pushable pushable
        +error AddPushable(Server.Pushable)
        +error SendTo(*Server.AppData)
        +error Serve()
        +error Setup(Server.Config)
    }
}

Server.PipeServer <|-- Sequencer.Sequencer
Server.Pushable *-- Sequencer.Sequencer
Server.Config <|-- Sequencer.SequencerConfig
Sequencer.SequencerConfig *-- Sequencer.Sequencer
Sequencer.SequenceMethod *-- Sequencer.SequencerConfig
@enduml