services:
  jqextractor:
    restart: always
    image: jqextractor:latest
    build:
      context: ../../.
      dockerfile: JQExtractor/Dockerfile.JQExtractor
    container_name: jqextractor
    volumes:
      - ./config:/config
    entrypoint: ["/jq-extractor", "--config", "/config/config.json"]
    environment:
      - LOG_LEVEL=DEBUG
      # - LOG_FILE=/config/jqextractor.log