services:
  sequencer:
    restart: always
    image: sequencer:latest
    build:
      context: ../../.
      dockerfile: Sequencer/Dockerfile.Sequencer
    container_name: sequencer
    volumes:
      - ./config:/config
    entrypoint: ["/sequencer", "--config", "/config/config.json"]
    environment:
      - LOG_LEVEL=DEBUG
      # - LOG_FILE=/config/sequencer.log