name: golang-linting

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-dir: []  # List your package directories here
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Download golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Fetches the golangci-lint binary without running it
          args: --help
          version: v1.60
      - name: Run golangci-lint
        run: |
          cd ${{ matrix.package-dir }}
          golangci-lint run --fix