name: sequencer-build-test-push

on:
  push:
    branches:
      - main

jobs:
    build-test-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Login to Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/SmartDCSITlimited/CDS-OTel-To-PV/sequencer
            
            - name: Build and export to Docker
              uses: docker/build-push-action@v6
              with:
                load: true
                context: .
                file: ./Sequencer/Dockerfile.Sequencer
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                
            - name: Test Docker Container
              working-directory: ./Sequencer/buildtest
              run: |
                  SEQUENCER_IMAGE=${{ steps.meta.outputs.tags }} ./run-test.sh
            
            - name: Push Docker Image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Sequencer/Dockerfile.Sequencer
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

